spring:
  config:
    import: optional:file:./application-secret.yml

  datasource:
    url: jdbc:postgresql://localhost:5432/restock
    username: postgres
    password: ${app.db-password}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true