import { zodResolver } from '@hookform/resolvers/zod'
import { useMutation, useQuery } from '@tanstack/react-query'
import { ArrowDownRight, ArrowRight, ArrowUpRight, GitCompareArrows, LoaderCircle, Minus, Play } from 'lucide-react'
import { useEffect } from 'react'
import { useForm } from 'react-hook-form'
import { z } from 'zod'
import { inventoryApi } from '@/api/endpoints'
import { EmptyPanel, ErrorPanel, Field, InlineError, LoadingPanel, Panel, numberFormatter } from '@/components/common/WorkbenchUi'
import { PageHeader } from '@/components/common/PageHeader'
import type { InventoryPolicyResponse, ScenarioCompareRequest, ScenarioCompareResponse } from '@/types/api'

const positive = z.string().min(1, '값을 입력해 주세요.').refine((value) => Number(value) > 0, '0보다 큰 숫자여야 합니다.')
const schema = z.object({ itemId: z.string().min(1), year: z.string().refine((value) => Number(value) >= 2000, '2000년 이상이어야 합니다.'), baselineOrdering: positive, baselineHolding: positive, alternativeOrdering: positive, alternativeHolding: positive })
type FormValues = z.infer<typeof schema>

export function ScenarioComparePage() {
  const itemsQuery = useQuery({ queryKey: ['items'], queryFn: async () => (await inventoryApi.items()).data })
  const form = useForm<FormValues>({ resolver: zodResolver(schema), defaultValues: { itemId: '', year: String(new Date().getFullYear()), baselineOrdering: '50000', baselineHolding: '1000', alternativeOrdering: '35000', alternativeHolding: '1400' } })
  useEffect(() => { if (!form.getValues('itemId') && itemsQuery.data?.[0]) form.setValue('itemId', String(itemsQuery.data[0].id)) }, [form, itemsQuery.data])
  const compare = useMutation({ mutationFn: async (body: ScenarioCompareRequest) => (await inventoryApi.compareScenarios(body)).data })
  const submit = form.handleSubmit((values) => compare.mutate({ itemId: Number(values.itemId), year: Number(values.year), baseline: { orderingCost: Number(values.baselineOrdering), annualHoldingCostPerUnit: Number(values.baselineHolding) }, alternative: { orderingCost: Number(values.alternativeOrdering), annualHoldingCostPerUnit: Number(values.alternativeHolding) } }))
  return <>
    <PageHeader eyebrow="SCENARIO LAB" index="08" title="시나리오 비교" description="주문비용과 보관비용 가정을 바꿨을 때 재고 정책이 어떻게 움직이는지 기준안과 대안을 나란히 비교합니다." />
    {itemsQuery.isLoading ? <LoadingPanel /> : itemsQuery.isError ? <ErrorPanel error={itemsQuery.error} onRetry={() => void itemsQuery.refetch()} /> : (itemsQuery.data?.length ?? 0) === 0 ? <Panel title="시나리오 조건"><EmptyPanel title="먼저 품목과 수요를 등록해 주세요" description="시나리오 비교는 실제 수요 이력이 있는 품목을 사용합니다." /></Panel> : <>
      <Panel eyebrow="SIMULATION CONTROL" title="비교 조건" className="mb-6"><form onSubmit={submit} noValidate>{compare.isError && <div className="px-5 pt-5"><InlineError error={compare.error}/></div>}<div className="grid gap-5 p-5 md:grid-cols-2"><Field label="품목"><select className="form-input" {...form.register('itemId')}>{itemsQuery.data?.map((item) => <option key={item.id} value={item.id}>{item.itemCode} · {item.name}</option>)}</select></Field><Field label="분석 연도" error={form.formState.errors.year?.message}><input type="number" min="2000" className="form-input" {...form.register('year')} /></Field></div><div className="grid gap-px border-y border-zinc-200 bg-zinc-200 lg:grid-cols-2"><ScenarioInputs title="BASELINE / 기준안" orderingName="baselineOrdering" holdingName="baselineHolding" form={form} /><ScenarioInputs title="ALTERNATIVE / 대안" orderingName="alternativeOrdering" holdingName="alternativeHolding" form={form} /></div><div className="flex justify-end bg-zinc-50 px-5 py-4"><button type="submit" className="button-primary" disabled={compare.isPending}>{compare.isPending ? <><LoaderCircle className="animate-spin" size={15}/> 비교 중</> : <><Play size={15}/> 시나리오 실행</>}</button></div></form></Panel>
      {compare.data ? <Comparison result={compare.data} /> : !compare.isError && <Panel eyebrow="SIMULATION OUTPUT" title="비교 결과"><EmptyPanel title="두 조건을 입력하고 시뮬레이션을 실행하세요" description="EOQ, 안전재고, 재주문점의 전후 차이와 비용 변화가 만든 의미를 함께 보여줍니다." action={<GitCompareArrows className="mx-auto text-[#4169e1]" size={28}/>} /></Panel>}
    </>}
  </>
}

function ScenarioInputs({ title, orderingName, holdingName, form }: { title: string; orderingName: 'baselineOrdering' | 'alternativeOrdering'; holdingName: 'baselineHolding' | 'alternativeHolding'; form: ReturnType<typeof useForm<FormValues>> }) {
  return <div className="space-y-5 bg-white p-5"><p className="font-mono text-[10px] font-bold tracking-[0.15em] text-zinc-500">{title}</p><Field label="1회 주문비용" error={form.formState.errors[orderingName]?.message}><div className="relative"><span className="absolute inset-y-0 left-3 flex items-center text-sm text-zinc-500">₩</span><input className="form-input pl-8 tabular-nums" inputMode="decimal" {...form.register(orderingName)} /></div></Field><Field label="연간 단위당 보관비용" error={form.formState.errors[holdingName]?.message}><div className="relative"><span className="absolute inset-y-0 left-3 flex items-center text-sm text-zinc-500">₩</span><input className="form-input pl-8 tabular-nums" inputMode="decimal" {...form.register(holdingName)} /></div></Field></div>
}

function Comparison({ result }: { result: ScenarioCompareResponse }) {
  const metrics = [{ key: 'EOQ', label: '경제적 주문량', before: result.baseline.economicOrderQuantity, after: result.alternative.economicOrderQuantity, diff: result.difference.economicOrderQuantityDifference }, { key: 'SS', label: '안전재고', before: result.baseline.safetyStock, after: result.alternative.safetyStock, diff: result.difference.safetyStockDifference }, { key: 'ROP', label: '재주문점', before: result.baseline.reorderPoint, after: result.alternative.reorderPoint, diff: result.difference.reorderPointDifference }]
  return <div className="space-y-6"><section className="grid gap-3 lg:grid-cols-3">{metrics.map((metric) => <div key={metric.key} className="rounded-xl border border-white bg-white p-5 shadow-[0_8px_24px_rgba(15,23,42,0.08)]"><div className="flex items-center justify-between"><p className="text-[10px] font-bold tracking-[0.14em] text-zinc-500">{metric.label}</p><span className="font-mono text-[10px] text-[#4169e1]">{metric.key}</span></div><div className="mt-6 flex items-end justify-between gap-3"><div><span className="text-xs text-zinc-400">기준</span><p className="mt-1 text-xl font-semibold">{numberFormatter.format(metric.before)}</p></div><ArrowRight className="mb-1 text-zinc-300" size={17}/><div className="text-right"><span className="text-xs text-zinc-400">대안</span><p className="mt-1 text-xl font-semibold text-[#3159d4]">{numberFormatter.format(metric.after)}</p></div></div><Difference value={metric.diff}/></div>)}</section><Panel eyebrow="DECISION INTERPRETATION" title="변화 해석"><div className="grid gap-0 lg:grid-cols-[0.85fr_1.15fr]"><PolicySnapshot label="BASELINE" data={result.baseline}/><div className="bg-gradient-to-br from-[#1c2127] to-[#0d1014] p-6 text-white md:p-8"><p className="text-[10px] font-bold tracking-[0.18em] text-[#91a4ff]">WHAT CHANGED</p><h3 className="mt-4 text-2xl font-semibold tracking-tight">대안의 주문 단위는 {describeChange(result.difference.economicOrderQuantityDifference)}.</h3><p className="mt-4 text-sm leading-6 text-zinc-400">EOQ는 주문비용이 높을수록 커지고, 단위당 보관비용이 높을수록 작아집니다. 안전재고와 재주문점은 같은 품목·연도라면 수요 변동과 리드타임이 같아 일반적으로 변하지 않습니다.</p><div className="mt-6 rounded-lg border border-white/10 bg-white/5 p-4 text-sm text-zinc-300">대안 기준: <strong className="text-white">{numberFormatter.format(result.alternative.economicOrderQuantity)}개씩 주문</strong>, 재고가 <strong className="text-white">{numberFormatter.format(result.alternative.reorderPoint)}개</strong>에 도달할 때 발주 검토</div></div></div></Panel></div>
}

function Difference({ value }: { value: number }) { const Icon = value > 0 ? ArrowUpRight : value < 0 ? ArrowDownRight : Minus; return <p className={`mt-5 flex items-center gap-1.5 text-xs font-semibold ${value > 0 ? 'text-emerald-700' : value < 0 ? 'text-rose-700' : 'text-zinc-500'}`}><Icon size={14}/>{value > 0 ? '+' : ''}{numberFormatter.format(value)}개</p> }
function PolicySnapshot({ label, data }: { label: string; data: InventoryPolicyResponse }) { return <div className="bg-white p-6 md:p-8"><p className="font-mono text-[10px] font-bold tracking-[0.15em] text-zinc-400">{label} / GRADE {data.abcGrade}</p><h3 className="mt-3 text-xl font-semibold text-zinc-950">{data.itemName}</h3><dl className="mt-6 space-y-3 text-sm"><div className="flex justify-between border-b border-zinc-100 pb-3"><dt className="text-zinc-500">연간 수요</dt><dd className="font-semibold">{numberFormatter.format(data.annualDemand)}개</dd></div><div className="flex justify-between border-b border-zinc-100 pb-3"><dt className="text-zinc-500">서비스율</dt><dd className="font-semibold">{data.serviceLevel}%</dd></div><div className="flex justify-between"><dt className="text-zinc-500">수요 표준편차</dt><dd className="font-semibold">{numberFormatter.format(data.dailyDemandStandardDeviation)}</dd></div></dl></div> }
function describeChange(value: number) { if (value > 0) return `${numberFormatter.format(value)}개 증가했습니다`; if (value < 0) return `${numberFormatter.format(Math.abs(value))}개 감소했습니다`; return '기준안과 같습니다' }
